a=int(input("Enter the value of a"))
b=int(input("Enter the value of b"))
print()
print("sum of a and b using '+' operator: ",(a+b))
print()
print("difference of a and b using '-' operator: ",(a-b))
print()
print("product of a and b using '*' operator: ",(a*b))
print("divisionn of a and b using '\' operator: ",(a/b))
print("floor division of a and b using '//' operator: ",(a//b))
print("modulous of a and b using '%' operator: ",(a%b))
print("exponentiation of a raise to b using '**' operator: ",(a**b))